version: "3.7"
services:
  app:
    image: node:12-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm run start:dev"
  neo4j:
    image: neo4j:latest
    volumes:
      - ~/neo4j/data:/data
      - ~/neo4j/logs:/logs
      - ~/neo4j/import:/var/lib/neo4j/import
      - ~/neo4j/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["graph-data-science"]
    restart: always
